# training config
global_config:
    seed: 231

trainer_config:
    max_epochs: 8000
    validation_interval: 1
    early_stopping_patience: 100

data_config:
    train_batch_size: 32
    val_batch_size: 32
    test_batch_size: 32
    
scheduler_config:
    RLROP_factor: 0.8
    RLROP_patience: 25
    RLROP_cooldown: 25
    RLROP_threshold: 0.001
    EXLR_gamma: 0.999
    warmup_epoch: 25
    type: RLROP

optimizer_config:
    learning_rate: 0.001
    force_ratio: 0.999
    gradient_clip_val: 10
    ema_decay: 0.99
    weight_decay: 0.0

    monitor: val_loss/val_loss
    mode: min


# model_config
model_config:
    rbf: nexpnorm
    max_z: 151
    rbf_trainable: false
    z_hidden_dim: 512
    ef_dim: 16
    hidden_dim: 512
    inner_layer_num: 4
    outer_layer_num: 1

    subg_cutoff: 5.0
    cutoff: 13.0
    
    activation_fn: ssp
    ablation_innerGNN: false

    extend_r: 5.0

    C_power: 1.

    max_neighbor: 50

